* Álmodó kövek (M.A.G.U.S.)
** Háttérinfók
*** Háttérsztori
    - Az első manifesztációs háború idején, amikor az öt kyr isten öltött testet, Morgena egyik halhatatlan
      szolgáját, Shar'all-t, bebörtönzik Quiphann város Sogron-templomának pokolkútjába.
    - A káoszkor idején a város elnéptelenedik, a sogron hívők elmenekülnek.
    - Már a hetedkorban, egy Noir pap felfedezi a templomot, és a kútból jövő jóslatokról számol be. A Noir
      papok el is foglalják, hogy tanulmányozzák a jóslatokat. A templomból zarándokhely lesz.
    - A jóslatokat többen is megfejtik, a Morgena hívők rájönnek, hogy egy Morgena angyal rejtőzik a kútban.
      Elfoglalják a templomot, megölik a Noir papokat, és átveszik a helyüket.
*** Hatalmi felek és motivációik
** Bemesélés, utazás a helyszínre
*** Erion felé
    Kétvárosból elindulnak Erion felé. Út közben Kro egy ötlettel fordul hozzájuk.
**** Kro kérése
     - Lenne egy ötletem, hogy hova menjünk. Úgy döntöttem, hogy antyss-járást akarok tanulni. Van egy régi
       ismerősöm még abból az időből, amikor Erenben utazgattam. Egy Noir pap. Ő biztosan meg tudna tanítani.
       Amikor legutóbb beszéltem vele, egy ősrégi kyr romtemplomba tartott a társaival együtt, mert valamiféle
       jóslatra bukkantak... már nem is emlékszem mi volt a neve a romvárosnak... Kvikpan, vagy Quipkan, valami
       ilyesmi. Az viszont biztos, hogy Daroveen mellett volt. Van kedvetek elkísérni az úton?
**** Erionban
     Találnak egy hajót, ami az Ilanor-i fővárosba tart, Dorian-ba. A hajó két nap múlva indul, addig van idejük
     bevásárolni.
*** Hajóút Erenbe
    Megállók:
**** Bemesélés, megbízás (Murák)
     A hajóúton (Murák) odamegy hozzájuk, érdeklődik merre tartanak, és miután kiderül, hogy ugyanoda, megkéri
     őket, hogy tartsanak vele. Akár a levelet is megmutathatja, amiben Daroveen grófja kéri a segítségét.
***** A levél
      Kedves barátom!

      A klánja vezetői ajánlották a figyelmembe, és elismeréssel nyilatkoztak a képességeiről és bátorságáról.
      Az Istenek is a hősöket és nem a gyávákat pártolják - magam is erre gondoltam, amikor a híre a fülembe
      jutott. Nekem is olyan emberre van szükségem, mint Ön, barátom, hiszen Dearoveen városában emberéletek
      forognak kockán, a magaméról nem is beszélve. Bővebbet majd személyesen. Ha sikerrel jár, hírnevének
      megfelelő jutalomban részesül. Siessen!

      Őszinte tisztelője: Merghon cwa Tissar, Daroveen grófja
      (négy hónappal ezelőtti dátum)
*** Érkezés, szállás az utolsó fogadóban
** Átkelés a komppal
*** NJK-k az úton
** A városban
*** Találkozás a gróffal
*** Nyomozás
*** Szállás a fogadóban
**** A tolvajok támadása
